#!/usr/bin/python2
# encoding: utf-8
from ek import *

def testdb():
    # Some test data from my own RP-1 game
    Redstone = EngineFamily("NAA-75-110", "Ethanol/LOx booster engine developed from German Aggregat 4.")
    DavyStage = StageFamily("Davy", Redstone, None)
    DavyShort = Stage("Davy 0/1", DavyStage, description="Short-stage booster to fit 20t pad.")
    DavyLong = Stage("Davy 2/3", DavyStage, description="Full-length Davy booster.")
    Aerobee = EngineFamily("Aerobee", "Early pressure-fed hypergolic (aniline/furfuryl/nitric) engine originally for sounding rockets.", vac=True)
    XASR = Engine("XASR-1", Aerobee)
    Ten = Engine("AJ10-27", Aerobee, "Early pressure-fed hypergolic (aniline/furfuryl/nitric) upper stage engine.")
    AJ10 = EngineFamily("AJ10", "Pressure-fed hypergolic (UDMH/nitric) upper stage engine.", vac=True)
    AJ10_37 = Engine("AJ10-37", AJ10)
    Blue = StageFamily("Blue", XASR, "Designation for generally unguided XASR-1 kick stages.", vac=True)
    Davy = LVFamily("Davy", "The Agency's first large rockets, built around the booster stage of the same name.")
    Davy01Family = LV("Davy 0/1", Davy, "Early model Davy rockets, lacking orbital capability.")
    Davy0 = LV("Davy 0", Davy01Family, "Flying the Short-Stage Davy without an upper stage, either for booster development or as a heavy sounding rocket.", DavyShort)
    Davy0B = LV("Davy 0B", Davy01Family, "Upper stage used for a boost-back maneuver to overfly land as a sounding rocket.", DavyShort, Blue)
    AbleStage = StageFamily("Able", AJ10, "Early pressure-fed hypergolic upper stage.", vac=True)
    TwinTen = Stage("Twin-Ten", AbleStage, Ten, "Very early upper stage.", 2)
    Davy1 = LV("Davy 1/1A", Davy01Family, "Two-stage sounding rocket for booster development.", DavyShort, TwinTen)
    Davy1B = LV("Davy 1B", Davy01Family, "Three-stage sounding rocket for booster development.", DavyShort, TwinTen, Blue)
    TripleTen = Stage("Triple-Ten", AbleStage, Ten, "Very early upper stage.", 3)
    Davy2Family = LV("Davy 2x", Davy, "Very early orbital rocket for small payloads.", DavyLong, TripleTen, Blue)
    Davy2 = LV("Davy 2", Davy2Family, "Very early orbital rocket for small payloads.", DavyLong, TripleTen, Blue)
    Davy2A = LV("Davy 2A", Davy2Family, "Very early orbital rocket for small payloads.  With two short Tens as strap-on boosters.")
    Davy2B = LV("Davy 2B", Davy2Family, "Very early orbital rocket for small payloads.  With four short Tens as strap-on boosters.")
    Davy3 = LV("Davy 3", Davy, "Similar to the Davy 2, but short-fuelled to reduce time-to-orbit at the cost of even tinier payload.", DavyLong, TripleTen, Blue)
    Davy3ST = LV("Davy 3S/T", Davy)
    Davy3S = LV("Davy 3S", Davy3ST, "Something of a misnomer, the Davy 3S uses the Short-Stage Davy to launch a tiny payload from a 20t pad.", DavyShort, TripleTen, Blue)
    Able0 = Stage("Able 0", AbleStage, AJ10_37)
    Davy3T = LV("Davy 3T", Davy3ST, "Development of the Davy 3S using upgraded upper stages.", DavyShort, Able0, Blue)
    LR79 = EngineFamily("LR79", "Gas-generator kerolox booster engine.")
    S3 = Engine("S-3", LR79, "Prototype gas-generator kerolox booster engine.")
    NewtonStage = StageFamily("Newton", LR79, "Workhorse booster stage, Ø=2.4m.")
    Newton01 = Stage("Newton 0/1", NewtonStage, S3)
    Newton = LVFamily("Newton", "Workhorse launch vehicles based on the Newton family of booster stages", NewtonStage)
    Newton0 = LV("Newton 0", Newton, "Booster development flight", Newton01)
    NewtonAx = LV("Newton Ax", Newton, "Newton/Able workhorse SLLV.", Newton, AbleStage)
    Newton1Family = LV("Newton 1x", NewtonAx, "Early Newton/Able workhorse.", Newton01, Able0)
    Newton1 = LV("Newton 1", Newton1Family)
    Newton1A = LV("Newton 1A", Newton1Family, "Early Newton/Able with added kick stage.", Newton01, Able0, Blue)
    Able0Refresh = Stage("Able 0 Refresh", Able0, description="An improved version of the Able0 stage, with lighter tankage and better avionics; Ø=1.5m.")
    Newton1C = LV("Newton 1C", Newton1Family, None, Newton01, Able0Refresh)
    Castor = EngineFamily("Castor", "Solid-fuel strap-on booster.")
    CastorI = Engine("Castor I", Castor, "Early solid-fuel strap-on booster.")
    CastorStage = StageFamily("Castor", Castor, "Solid-fuel strap-on boosters.")
    CastorIx2 = Stage("Castor I x2", CastorStage, CastorI, None, 2)
    Newton1D = LV("Newton 1D", Newton1Family, "Augmented Newton/Able for lunar probes.", CastorIx2, Newton01, Able0Refresh, Blue)
    S3D = Engine("S-3D", LR79)
    Newton2Stage = Stage("Newton 2", NewtonStage, S3D)
    AJ10_42 = Engine("AJ10-42", AJ10)
    Able1 = Stage("Able 1", AbleStage, AJ10_42)
    NewtonA2Family = LV("Newton A2x", NewtonAx, "Newton/Able workhorse.", Newton2Stage, Able1)
    Newton2 = LV("Newton 2", NewtonA2Family, "Newton/Able workhorse.", Newton2Stage, Able1)
    Newton2A = LV("Newton 2A", NewtonA2Family, "Augmented Newton/Able for lunar probes.", CastorIx2, Newton2Stage, Able1, Blue)
    Newton2C = LV("Newton 2C", NewtonA2Family, "Newton/Able with added kick stage.", Newton2Stage, Able1, Blue)
    XLR81 = EngineFamily("XLR81", "Bell Agena vacuum engine, gas-generator, UDMH/nitric.", vac=True)
    XLR81BA5 = Engine("XLR81-BA-5", XLR81, "Early hypergolic gas-generator upper-stage engine; rated for 2m burn.")
    Agena = StageFamily("Agena", XLR81, "Versatile upper stage using hypergolic propellants.", vac=True)
    AgenaA = Stage("Agena A", Agena, XLR81BA5)
    NewtonBx = LV("Newton Bx", Newton, "Newton/Agena small-medium lift workhorse.", Newton, Agena)
    NewtonB2 = LV("Newton B2", NewtonBx, "Prototype Newton/Agena.", Newton2Stage, AgenaA, Blue)
    MB31 = Engine("MB-3-1", LR79, "Production gas-generator kerolox booster engine.")
    Newton3Stage = Stage("Newton 3", NewtonStage, MB31)
    NewtonB3 = LV("Newton B3", NewtonBx, "Newton/Agena workhorse.", Newton3Stage, AgenaA)
    AJ10_101A = Engine("AJ10-101A", AJ10)
    Able2 = Stage("Able 2", AbleStage, AJ10_101A)
    NewtonA3 = LV("Newton A3", NewtonAx, "Newton/Able workhorse.", Newton3Stage, Able2)
    NewtonA3A = LV("Newton A3A", NewtonA3, "Newton/Able with added kick stage.", Newton3Stage, Able2, Blue)
    NewtonB3A = LV("Newton B3A", NewtonB3, "Newton/Agena with added kick stage.", Newton3Stage, AgenaA, Blue)
    LR105 = EngineFamily("LR105", "Kerolox gas-generator sustainer engine, rated for nearly six minutes burn time.")
    LR105NA3 = Engine("LR105-NA-3", LR105, "Prototype kerolox gas-generator sustainer engine.")
    TartagliaStage = StageFamily("Tartaglia", LR105, "Kerolox sustainer stage, Ø=2.4m.")
    TartagliaA = Stage("Tartaglia A", TartagliaStage, LR105NA3)
    Tartaglia = LVFamily("Tartaglia", "Suborbital development flights of the Tartaglia sustainer stage.", TartagliaStage)
    Tartaglia0 = LV("Tartaglia 0", Tartaglia, "Suborbital test flight of Tartaglia A sustainer stage.", TartagliaA)
    LeibnitzBooster = StageFamily("Leibnitz LFB", LR79, "Newton-derived liquid-fuel boosters.", 2)
    LeibnitzAStage = Stage("Leibnitz A LFB", LeibnitzBooster, MB31, "Liquid fuel boosters based on Newton 3.")
    Leibnitz = LVFamily("Leibnitz", "Parallel-staged kerolox LV for medium lift, GLOM up to 150t.", LeibnitzBooster, TartagliaStage)
    LeibnitzA = LV("Leibnitz A", Leibnitz, "Prototype parallel-staged kerolox LV.", LeibnitzAStage, TartagliaA)
    LeibnitzAB = LV("Leibnitz AB", LeibnitzA, "Prototype Leibnitz/Agena.", LeibnitzAStage, TartagliaA, AgenaA)
    Napier = StageFamily("Napier", XLR81, "Spaceplane with one-man crew.", vac=True)
    NapierA = Stage("Napier (1958)", Napier, XLR81BA5, "Initial configuration of Napier spaceplane; first manned spaceflights.")
    LeibnitzAH = LV("Leibnitz AH", LeibnitzA, "Prototype Leibnitz/Napier.", LeibnitzAStage, TartagliaA, NapierA)
    MB32 = Engine("MB-3-2", LR79, "Upgraded gas-generator kerolox booster engine.")
    Newton4Stage = Stage("Newton 4/5/6", NewtonStage, MB32)
    AJ10_142 = Engine("AJ10-142", AJ10)
    Able3 = Stage("Able 3", AbleStage, AJ10_142, "Ultimate refined version of Able upper stage; for later related development see Delta.")
    NewtonA4 = LV("Newton A4", NewtonAx, "Final variant of the venerable Newton/Able workhorse.", Newton4Stage, Able3)
    NewtonB4 = LV("Newton B4", NewtonBx, "Newton/Agena workhorse.", Newton4Stage, AgenaA)
    NewtonB4Blue = LV("Newton B4+", NewtonB4, "Newton/Agena workhorse with kick stage.", Newton4Stage, AgenaA, Blue)
    LeibnitzBStage = Stage("Leibnitz B LFB", LeibnitzBooster, MB32, "Liquid fuel boosters based on Newton 4.")
    LR105NA5 = Engine("LR105-NA-5", LR105)
    TartagliaB = Stage("Tartaglia B", TartagliaStage, LR105NA5)
    LeibnitzB = LV("Leibnitz B", Leibnitz, None, LeibnitzBStage, TartagliaB)
    LeibnitzBH1 = LV("Leibnitz BH1", LeibnitzB, "Early Leibnitz/Napier with upgraded kerolox engines.", LeibnitzBStage, TartagliaB, NapierA)
    XLR81BA7 = Engine("XLR81-BA-7", XLR81, "Restartable hypergolic gas-generator upper-stage engine; rated for two burns totalling up to four minutes.")
    AgenaB = Stage("Agena B", Agena, XLR81BA7, "First upper stage with relight capability; generally unprecedented performance.")
    NewtonB5 = LV("Newton B5", NewtonBx, "Newton/Agena workhorse, introduced restartable Agena B.", Newton4Stage, AgenaB)
    AJ10_104 = Engine("AJ10-104", AJ10, "First 'Delta' variant of the AJ10; unlimited restarts.")
    Delta = StageFamily("Delta", AJ10, "Restartable pressure-fed hypergolic upper stage.", vac=True)
    DeltaD = Stage("Delta D", Delta, AJ10_104)
    NewtonD4 = LV("Newton D4", Newton, "Prototype Newton/Delta.", Newton4Stage, DeltaD)
    NapierB = Stage("Napier (1959)", Napier, XLR81BA7, "Upgraded configuration of Napier spaceplane; increased reliability.")
    LeibnitzBH2 = LV("Leibnitz BH2", LeibnitzB, "1959-standard Leibnitz/Napier.", LeibnitzBStage, TartagliaB, NapierB)
    LeibnitzBB = LV("Leibnitz BB", LeibnitzB, "Leibnitz/Agena medium-lift LV.", LeibnitzBStage, TartagliaB, AgenaB)
    XLR81BA11 = Engine("XLR81-BA-11", XLR81, "Adds propellant sumps and slightly increased Isp.")
    AgenaD = Stage("Agena D", Agena, XLR81BA11)
    LeibnitzBB4 = LV("Leibnitz BB4", LeibnitzBB, "Leibnitz/Agena medium-lift LV.", LeibnitzBStage, TartagliaB, AgenaD)
    NewtonB6 = LV("Newton B6", NewtonBx, "A further slight upgrade to the Newton/Agena workhorse.", Newton4Stage, AgenaD)
    H1Family = EngineFamily("H-1", "Gas-generator kerolox engine, a simplified and uprated development of LR79 technology.")
    H1 = Engine("H-1-SaturnI", H1Family)
    LockeStage = StageFamily("Locke", H1Family, "Workhorse booster stage (based on Newton).")
    Locke01 = Stage("Locke 0/1", LockeStage, H1)
    Locke = LVFamily("Locke", "Workhorse launch vehicles based on the Locke family of booster stages (developed from, and replacing, the Newton family).", LockeStage)
    Locke0 = LV("Locke 0", Locke, "Booster development flight of prototype Locke stage with dummy upper stage.", Locke01)
    Locke1B = LV("Locke 1B", Locke, "Locke/Agena workhorse, replacement for Newton Bx series.", Locke01, AgenaD)
    LR105NA6 = Engine("LR105-NA-6", LR105)
    TartagliaC = Stage("Tartaglia C", TartagliaStage, LR105NA6)
    TartagliaC0 = LV("Tartaglia C0", Tartaglia, "Suborbital test flights of Tartaglia C sustainer stage.", CastorIx2, TartagliaC)
    LeibnitzCStage = Stage("Leibnitz C LFB", LeibnitzBooster, H1, "Liquid fuel boosters based on Locke 1.")
    LeibnitzC = LV("Leibnitz C", Leibnitz, "Revamped Leibnitz using Locke-1-derived boosters.", LeibnitzCStage, TartagliaC)
    LeibnitzCB = LV("Leibnitz CB", LeibnitzC, "Leibnitz/Agena medium-lift LV.", LeibnitzCStage, TartagliaC, AgenaD)
    LeibnitzCB1 = LV("Leibnitz CB1", LeibnitzCB, "Leibnitz/Agena medium-lift LV with added retro stage.", LeibnitzCStage, TartagliaC, AgenaD, Blue)
    TartagliaCA0 = LV("Tartaglia CA0", TartagliaC0, "Suborbital test flight of Tartaglia C sustainer (with Able 3 upper stage).", CastorIx2, TartagliaC, Able3)
    LeibnitzCD = LV("Leibnitz CD", LeibnitzC, "Leibnitz/Delta, for direct GEO insertion of small payloads.", LeibnitzCStage, TartagliaC, DeltaD)
    RL10 = EngineFamily("RL10", "Expander cycle hydrolox engine.", vac=True)
    RL10A1 = Engine("RL10A-1", RL10, "Prototype hydrolox engine.")
    Centaur = StageFamily("Centaur", RL10, "High-energy hydrolox upper stage.", vac=True)
    CentaurA = Stage("Centaur A", Centaur, RL10A1, "Prototype hydrolox upper stage.")
    Locke1C = LV("Locke 1C", Locke, "Locke/Centaur medium-lift LV.", Locke01, CentaurA)
    LeibnitzCC = LV("Leibnitz CC", LeibnitzC, "Leibnitz/Centaur, for high-energy launches.", LeibnitzCStage, TartagliaC, CentaurA)
    GrotiusBooster = StageFamily("Grotius LFB", H1Family, "Locke-derived liquid-fuel boosters.", 3)
    Grotius1Stage = Stage("Grotius 1 LFB", GrotiusBooster, H1)
    GrotiusFamily = LVFamily("Grotius", "Like Leibnitz but with more than two LFBs.", GrotiusBooster, TartagliaStage)
    DeltaDMini = Stage("Delta D Mini", Delta, AJ10_104, "Short-tank Delta D stage for use above a Centaur.")
    Grotius1 = LV("Grotius 1", GrotiusFamily, "Hotch-potch LV to place heavy comsat in GEO.", Grotius1Stage, TartagliaC, CentaurA, DeltaDMini)
    NapierD = Stage("Napier (1960)", Napier, XLR81BA11, "1960 configuration of Napier spaceplane; increased on-orbit endurance.")
    LeibnitzCH = LV("Leibnitz CH", LeibnitzC, "1960-standard Leibnitz/Napier.", LeibnitzCStage, TartagliaC, NapierD)
    LeibnitzCC2 = LV("Leibnitz CC2/CE", LeibnitzCC, "Short Delta D as either crasher (for lunar landings, as Leibnitz CC2) or kick stage (for GEO insertion, as Leibnitz CE).", LeibnitzCStage, TartagliaC, CentaurA, DeltaDMini)
    Napier2 = StageFamily("Napier 2", XLR81, "Spaceplane with two-man crew.", vac=True)
    Napier2D = Stage("Napier 2 (1960)", Napier2, XLR81BA11, "Initial configuration of Napier 2 spaceplane.")
    LeibnitzCH3 = LV("Leibnitz CH3", LeibnitzC, "1960-standard Leibnitz/Napier 2.", LeibnitzCStage, TartagliaC, Napier2D)
    Locke1D = LV("Locke 1D", Locke, "Locke/Delta SLLV, replacement for Newton Ax/D4.", Locke01, DeltaD)
    AJ10_138 = Engine("AJ10-138", AJ10, "Advanced AJ10 as used on Transtage.  4 ignitions.")
    DeltaT = Stage("Delta T", Delta, AJ10_138)
    DeltaTMini = Stage("Delta T Mini", Delta, AJ10_138, "Short-tank Delta T stage for use above a Centaur.")
    LeibnitzCE3 = LV("Leibnitz CE3", LeibnitzCC, "Kick stage upgraded to Delta T engine.", LeibnitzCStage, TartagliaC, CentaurA, DeltaTMini)
    RL10A31 = Engine("RL10A-3-1", RL10, "Early hydrolox engine.")
    CentaurB = Stage("Centaur B", Centaur, RL10A31, "Early hydrolox upper stage.")
    LeibnitzCC5 = LV("Leibnitz CC5", LeibnitzCC2, "LV for lunar landings, with upgraded Centaur", LeibnitzCStage, TartagliaC, CentaurB, DeltaDMini)
    H1B = Engine("H-1-SaturnIB", H1Family)
    Locke2 = Stage("Locke 2", LockeStage, H1B)
    XLR81BA13 = Engine("XLR81-BA-13", XLR81, "Up to 15 ignitions; otherwise same performance as -11.")
    AgenaF = Stage("Agena F", Agena, XLR81BA13)
    Locke2B0 = LV("Locke 2B0", Locke, "Test flight of upgraded Locke and Agena (GATV) engines.", Locke2, AgenaF)
    LR105NA71 = Engine("LR105-NA-7.1", LR105)
    TartagliaD = Stage("Tartaglia D", TartagliaStage, LR105NA71)
    LeibnitzDStage = Stage("Leibnitz D LFB", LeibnitzBooster, H1B, "Liquid fuel boosters based on Locke 2.")
    LeibnitzD = LV("Leibnitz D", Leibnitz, "Incremental upgrade of the Leibnitz MLLV.", LeibnitzDStage, TartagliaD)
    LeibnitzDC = LV("Leibnitz DC", LeibnitzD, "Incremental upgrade of Leibnitz/Centaur high-energy launch vehicle.", LeibnitzDStage, TartagliaD, CentaurB)
    Model8096_39 = Engine("Model8096-39", XLR81, "Improved propellant raises the Isp and thrust.  Back to two ignitions though.")
    AgenaG = Stage("Agena G", Agena, Model8096_39)
    Locke2B = LV("Locke 2B", Locke, "Second-generation Locke/Agena workhorse, ~1.4t to LEO.", Locke2, AgenaG)
    Napier2F = Stage("Napier 2 (Nov61)", Napier2, XLR81BA13, "Upgrade of Napier 2 spaceplane with multi-restart OPS.")
    LeibnitzDH = LV("Leibnitz DH", LeibnitzD, "November 1961 standard Leibnitz/Napier 2.", LeibnitzDStage, TartagliaD, Napier2F)
    LeibnitzDC2 = LV("Leibnitz DC2/DE", LeibnitzDC, "Incremental upgrade of CC2/CE family, for lunar missions including LLO propellant depot, and GEO satellites.", LeibnitzDStage, TartagliaD, CentaurB, DeltaTMini)
    J2 = EngineFamily("J-2", "Large gas-generator hydrolox engine.", vac=True)
    J2P = Engine("J-2-200klbf", J2, "Prototype large hydrolox engine.")
    Eulerian = StageFamily("Eulerian", J2, "Large hydrolox upper stage.", vac=True)
    EulerianA = Stage("Eulerian A", Eulerian, J2P, "Prototype large hydrolox upper stage.")
    Volta = StageFamily("Volta", H1Family, "Large clustered-engine kerolox booster stage.", 4)
    VoltaA = Stage("Volta A", Volta, H1B, "Four-engine kerolox booster stage.", 4)
    Euler = LVFamily("Euler", "The beginnings of heavy lift.", Volta, Eulerian)
    Euler0 = LV("Euler 0", Euler, "Test flight of first Volta and Eulerian stages.", VoltaA, EulerianA)
    RL10A33 = Engine("RL10A-3-3", RL10)
    CentaurC = Stage("Centaur C", Centaur, RL10A33)
    LeibnitzDE2 = LV("Leibnitz DE2", LeibnitzDC, "Incremental upgrade of DE family, for GEO satellites and lunar propellant deliveries.", LeibnitzDStage, TartagliaD, CentaurC, DeltaTMini)
    EulerA = LV("Euler A", Euler, "High-energy launch, Euler/Centaur.", VoltaA, EulerianA, CentaurC)
    LeibnitzDD = LV("Leibnitz DD", LeibnitzD, "Incremental upgrade of Leibnitz/Delta, a useful space tug.", LeibnitzDStage, TartagliaD, DeltaT)
    NapierF = Stage("Napier (1962)", Napier, XLR81BA13, "1962 configuration of Napier spaceplane; multi-restart OPS.")
    LeibnitzDH3 = LV("Leibnitz DH3", LeibnitzD, "1962-standard Leibnitz/Napier 1.", LeibnitzDStage, TartagliaD, NapierF)
    LeibnitzDB = LV("Leibnitz DB", LeibnitzD, "Leibnitz/Agena medium-lift LV.", LeibnitzDStage, TartagliaD, AgenaG)
    NapierF2 = Stage("Napier (Oct62)", Napier, XLR81BA13, "Late 1962 configuration of Napier 1 spaceplane; converted to two-seater.") # Similar to Napier2F, but not identical.
    LeibnitzDH5 = LV("Leibnitz DH5", LeibnitzD, "Late-1962 standard Leibnitz/Napier 1 (two-seat).", LeibnitzDStage, TartagliaD, NapierF2)
    LeibnitzDE3 = LV("Leibnitz DE3", LeibnitzDC, "Incremental upgrade of (CC5) LV for lunar landings.", LeibnitzDStage, TartagliaD, CentaurC, DeltaDMini)

    launches = []
    def launch(name, y, m, d, lv, payload, dest, result):
        launches.append(Launch(name, date(y, m, d), lv, payload, dest, result))
    def paren(text):
        return Payload(None, None, text)

    launch("Davy 0",        1952,  8, 23, Davy0,        None, SO, 0)
    launch("Davy 1",        1952, 10,  6, Davy1,        None, SO, 0)
    launch("Davy 1A",       1952, 11, 23, Davy1,        None, SO, 0)
    launch("Davy 1B",       1953,  1, 19, Davy1B,       None, SO, 0)
    launch("Davy 0A",       1953,  2, 28, Davy0,        paren("Early film camera"), SO, 0)
    launch("Davy 2",        1953,  4, 24, Davy2,        paren("60kg SR core"), EO, -1)
    launch("Davy 2A",       1953,  6, 24, Davy2A,       paren("60kg SR core"), EO, 3)
    launch("Davy 2B",       1953,  8, 27, Davy2B,       Payload("Kepler 0", "First satellite to orbit the Earth!", "60kg SR core"), EO, 0)
    launch("Davy 2B₂",      1953, 10, 29, Davy2B,       paren("60kg SR core"), SO, 0)
    launch("Davy 0B",       1953, 12, 10, Davy0B,       paren("Early film camera"), SO, 0)
    launch("Davy 3",        1954,  4, 30, Davy3,        Payload("Kepler 1", None, "Explorer-1"), EO, -1)
    launch("Davy 3S",       1954,  6, 23, Davy3S,       paren("Explorer-1"), EO, 2)
    launch("Davy 3",        1954,  8, 22, Davy3,        Payload("Kepler 2", None, "Explorer-1"), EO, 0)
    launch("Davy 3S₂",      1954, 10, 14, Davy3S,       Payload("Kepler 3", None, "Explorer-1"), EO, 0)
    launch("Davy 3A",       1954, 12, 14, Davy3,        Payload("Bernoulli 1", "Atmospheric analysis satellite.", "Explorer-1"), EO, 0)
    launch("Newton 0",      1955,  1, 17, Newton0,      None, SO, -1)
    launch("Newton 0A",     1955,  3,  5, Newton1,      None, EO, 0)
    launch("Newton A1",     1955,  5,  7, Newton1,      paren("Scientific satellite"), EO, 1)
    launch("Davy 3SP",      1955,  6, 16, Davy3S,       paren("Explorer-1"), EPO, 2)
    launch("Newton A1A",    1955,  7,  8, Newton1A,     Payload("Kepler 4", "Scientific satellite"), EO, 0)
    launch("Newton A1B",    1955,  9, 13, Newton1A,     Payload("Kepler 5", "Scientific satellite"), HEO, 0)
    launch("Newton A1C",    1955, 12,  7, Newton1C,     paren("Controllable weather satellite"), EO, 2)
    launch("Davy 3T",       1956,  2, 22, Davy3T,       Payload("Kepler 6", "First polar-orbit satellite.", "Explorer-1"), EPO, 0)
    launch("Newton A1D",    1956,  3, 10, Newton1D,     Payload("Tycho 1", "First lunar mission!  Does not carry lunar-range comms."), LI, 0)
    launch("Newton A1C₂",   1956,  5, 19, Newton1C,     Payload("Bernoulli 2", "Controllable weather satellite."), LEO, 0)
    launch("Newton A1E",    1956,  9,  1, Newton1D,     Payload("Tycho 2", "Prototype lunar probe."), LF, 0)
    launch("Newton A2",     1956, 10, 25, Newton2,      Payload("Bernoulli 3", "Weather satellite."), LEO, 0)
    launch("Newton A2A",    1957,  1, 11, Newton2A,     Payload("Tycho 3", "Lunar probe with basic scientific instruments.  First pictures of lunar farside."), LF, 0)
    launch("Davy 3T₂",      1957,  1, 29, Davy3T,       Payload("Kepler 7", "Geodesy satellite."), SSO, 0)
    launch("Newton A2B",    1957,  2, 16, Newton2,      paren("Re-entry test vehicle; mass spectrometers"), LEO, 0)
    launch("Newton A2C",    1957,  3,  9, Newton2C,     Payload("Tycho 4"), LI, 0)
    launch("Newton A2D",    1957,  4,  9, Newton2,      paren("Photographic satellite with film return capsule"), LEO, 0)
    launch("Newton B2",     1957,  5,  2, NewtonB2,     Payload("Tycho 5"), LI, 0)
    launch("Newton B3",     1957,  6,  1, NewtonB3,     paren("Photographic satellite with film return capsule"), LEO, 0)
    launch("Newton A3",     1957,  6, 26, NewtonA3,     Payload("Bernoulli 4", "Weather satellite + magnetometer."), LEO, 0)
    launch("Newton A3A",    1957,  7, 11, NewtonA3A,    paren("Communications satellite"), EO, 3)
    launch("Newton B3A",    1957,  8, 13, NewtonB3A,    Payload("Tycho 6", "First lunar orbiter; good science return."), LO, 0)
    launch("Newton A3B",    1957,  9,  3, NewtonA3,     Payload("Bernoulli 5", "Weather satellite."), LEO, 0)
    launch("Tartaglia 0",   1957,  9,  9, Tartaglia0,   None, SO, 0)
    launch("Leibnitz AB1",  1957, 10, 15, LeibnitzAB,   Payload("Fermat 1", "First communications satellite."), EO, 0)
    launch("Newton A3B₂",   1957, 11,  4, NewtonA3,     Payload("Bernoulli 6", "Weather satellite."), LEO, 0)
    launch("Leibnitz AH1",  1958,  2, 27, LeibnitzAH,   Payload("NPF-1", "Test flight of Napier", "unmanned"), LEO, 3)
    launch("Newton A3C",    1958,  3,  7, NewtonA3,     Payload("Bernoulli 7", "Weather satellite."), LEO, 0)
    launch("Leibnitz AH2",  1958,  5, 26, LeibnitzAH,   Payload("NPF-2", "First human spaceflight.", "Timur Vasilyevykh"), LEO, 0)
    launch("Newton A4",     1958,  6,  4, NewtonA4,     Payload("Bernoulli 8", "Weather satellite."), LEO, 0)
    launch("Newton B4",     1958,  7,  3, NewtonB4Blue, Payload("Tycho 7", "Lunar magnetometry probe."), LO, 0)
    launch("Leibnitz BH1",  1958, 10, 25, LeibnitzBH1,  Payload("NEF-1", "Planned EVA mission; transatlantic abort due to Tartaglia failure.", "Vasily Sungatulin"), LEO, 2)
    launch("Newton B5",     1958, 10, 31, NewtonB5,     Payload("Fermat 2", "Communications satellite."), EO, 0)
    launch("Newton D4",     1958, 11, 11, NewtonD4,     paren("600kg lead ballast"), EO, 0)
    launch("Newton B4A",    1958, 12, 29, NewtonB4,     Payload("Pascal 1", "Second-generation weather satellite."), SSO, 0)
    launch("Leibnitz BH2",  1959,  2,  4, LeibnitzBH2,  Payload("NEF-1a", "EVA; 24 hours on orbit.", "Timur Vasilyevykh"), LEO, 0)
    launch("Newton B5B",    1959,  2, 10, NewtonB5,     Payload("Fermat 3", "Communications test satellite."), EO, 0)
    launch("Newton B5A",    1959,  4,  9, NewtonB5,     Payload("Pascal 2", "Second-generation weather satellite."), SSO, 0)
    launch("Leibnitz BB2",  1959,  6,  3, LeibnitzBB,   Payload("Copernicus 1", "First interplanetary probe."), VF, 0)
    launch("Leibnitz BH3",  1959,  7, 20, LeibnitzBH2,  Payload("NEF-2", "Rendezvous with Bernoulli 2.", "Vasily Sungatulin"), LEO, 0)
    launch("Newton B5C",    1959,  7, 28, NewtonB5,     paren("Photographic satellite with film return capsule"), LEO, 0)
    launch("Newton B5D",    1959,  8,  2, NewtonB5,     Payload("Mersenne 1", "Start of four-satellite comms network."), MEO, 0)
    launch("Leibnitz BB3",  1959,  9, 17, LeibnitzBB,   Payload("Fermat 4", "First comsat in Molniya orbit."), HEO, 0)
    launch("Newton D4A",    1959, 10,  4, NewtonD4,     Payload("Descartes 1", "RADAR mapping satellite."), EPO, 0)
    launch("Newton B5E",    1959, 10,  9, NewtonB5,     Payload("Mersenne 2", "Communications satellite, part of four-sat network."), MEO, 0)
    launch("Newton B5E₂",   1959, 11,  4, NewtonB5,     Payload("Mersenne 3", "Communications satellite, part of four-sat network."), MEO, 0)
    launch("Newton B5A",    1959, 11, 21, NewtonB5,     Payload("Pascal 3", "Second-generation weather satellite."), SSO, 0)
    launch("Newton B5E₃",   1959, 11, 24, NewtonB5,     paren("Mersenne communications satellite for four-sat network"), MEO, 2)
    launch("Locke 0",       1959, 12, 10, Locke0,       paren("8 tons lead ballast"), SO, 0)
    launch("Newton B6A",    1959, 12, 15, NewtonB6,     Payload("Mersenne 4", "Communications satellite, completes four-sat network."), MEO, 0)
    launch("Locke 1B1",     1959, 12, 27, Locke1B,      Payload("Fermat 5", "Communications test satellite."), EO, 0)
    launch("Newton B6",     1959, 12, 28, NewtonB6,     Payload("Pascal 4", "Second-generation weather satellite."), SSO, 0)
    launch("Tartaglia C0",  1960,  1,  5, TartagliaC0,  None, SO, -1)
    launch("Leibnitz BB4",  1960,  1, 21, LeibnitzBB4,  Payload("Tycho 8", "Lunar RADAR mapping."), LO, 0)
    launch("Tartaglia CA0", 1960,  1, 27, TartagliaCA0, None, SO, 0)
    launch("Leibnitz CB1",  1960,  2,  1, LeibnitzCB1,  Payload("Tycho 9", "Lunar film-return probe."), LF, 0)
    launch("Locke 1B2",     1960,  2,  3, Locke1B,      Payload("Boyle 1", "Sun-synchronous weather satellite."), SSO, 0)
    launch("Locke 1B3",     1960,  2, 10, Locke1B,      Payload("Kepler 8", "Scientific satellite."), LEO, 0)
    launch("Leibnitz CD1",  1960,  2, 19, LeibnitzCD,   Payload("Fermat 6", "First geostationary satellite; prototype comsat."), GEO, 0)
    launch("Locke 1B5",     1960,  2, 28, Locke1B,      paren("Communications test satellite."), EO, 2)
    launch("Leibnitz CB2",  1960,  3,  8, LeibnitzCB,   Payload("Fermat 7", "First comsat in Tundra orbit."), HEO, 0)
    launch("Locke 1B5₂",    1960,  3,  9, Locke1B,      Payload("Fermat 8", "Communications test satellite."), EO, 0)
    launch("Locke 1C0",     1960,  3, 31, Locke1C,      paren("1.5 tons lead ballast"), LEO, 0)
    launch("Leibnitz CB3",  1960,  4, 20, LeibnitzCB,   Payload("Tycho 10", "Lunar multispectral mapping."), LO, 0)
    launch("Locke 1B6",     1960,  4, 28, Locke1B,      Payload("Fermat 9", "Communications test satellite."), EO, 0)
    launch("Locke 1B7",     1960,  5, 13, Locke1B,      Payload("IRSat", "Scientific satellite."), HEO, 0)
    launch("Leibnitz CC1",  1960,  5, 14, LeibnitzCC,   Payload("Laplace 1", "First softlanding lunar probe.  Very limited science payload."), LS, 0) # Landed in Lowlands
    launch("Locke 1B4",     1960,  6,  7, Locke1B,      Payload("Descartes 2", "Biome mapping satellite."), EPO, 0)
    launch("Grotius 1",     1960,  6, 25, Grotius1,     Payload("Bacon 1", "Heavy comsat.", "2000CSP"), GEO, 0)
    launch("Leibnitz CH1",  1960,  7, 15, LeibnitzCH,   Payload("NEF-3", "48 hours on orbit.", "Vasily Sungatulin"), LEO, 0)
    launch("Grotius 1A",    1960,  8,  9, Grotius1,     Payload("Boyle 2", "Heavy weathersat.", "1837WSP"), GEO, 0)
    launch("Locke 1B8",     1960,  8, 17, Locke1B,      Payload("Boyle 3", "Sun-synchronous weather satellite."), SSO, 0)
    launch("Leibnitz CB4",  1960,  9, 18, LeibnitzCB,   Payload("Copernicus 2", "One of a pair of Mars fly-by probes."), MF, 0)
    launch("Leibnitz CB5",  1960,  9, 19, LeibnitzCB,   Payload("Copernicus 3", "One of a pair of Mars fly-by probes."), MF, 0)
    launch("Leibnitz CH2",  1960,  9, 22, LeibnitzCH,   Payload("NEF-4", "72 hours on orbit.", "Timur Vasilyevykh"), LEO, 0)
    launch("Leibnitz CC2",  1960, 10, 24, LeibnitzCC2,  Payload("Laplace 2", "Softlanding lunar probe with several scientific instruments."), LS, 0) # Landed in Mare Nubium
    launch("Leibnitz CH3",  1960, 11, 22, LeibnitzCH3,  Payload("NPF-3", "Test flight of Napier 2; one orbit", "unmanned"), LEO, 0)
    launch("Locke 1C1",     1960, 12,  1, Locke1C,      Payload("Boyle 4", "Sun-synchronous weather satellite."), SSO, 0)
    launch("Leibnitz CC3",  1960, 12, 11, LeibnitzCC2,  Payload("Laplace 3", "Softlanding lunar probe, upgraded version of Laplace 2."), LS, 0) # Landed in Aitken Basin
    launch("Leibnitz CB6",  1961,  1, 15, LeibnitzCB,   Payload("Copernicus 4", "Venus scientific orbiter."), VO, 0)
    launch("Locke 1D1",     1961,  2,  4, Locke1D,      Payload("Delta Target", "Simple docking target."), LEO, 0)
    launch("Leibnitz CH4",  1961,  2,  5, LeibnitzCH,   Payload("NEF-5", "Rendezvous and docking with Delta Target (Locke 1D1).", "Eric Welch"), LEO, (0, 1)) # one H-1 failed but did not kill the mission
    launch("Leibnitz CE1",  1961,  2, 16, LeibnitzCC2,  Payload("Bacon 2", "Comsat.", "788CSP"), GEO, -1) # forgot to pressurise DeltaD tank (oops!)
    launch("Locke 1B9",     1961,  3, 16, Locke1B,      Payload("Lagrange Core Node", "First component of our Space Station."), LEO, 1)
    launch("Leibnitz CH5",  1961,  3, 20, LeibnitzCH3,  Payload("NPF-4", "First two-man space mission.", ("Brian Newman", "Nikolay Tikhonov")), LEO, 0)
    launch("Locke 1B9a",    1961,  4, 15, Locke1B,      Payload("Lagrange Core Node (replacement)", "First component of our Space Station."), LEO, 0)
    launch("Leibnitz CE2",  1961,  4, 24, LeibnitzCC2,  Payload("Bacon 2A", "Comsat.", "788CSP"), GEO, (0, 4)) # mini-DeltaD died with 250m/s to go
    launch("Leibnitz CC4",  1961,  5, 26, LeibnitzCC2,  Payload("Laplace 4", "Softlanding lunar probe, cost-optimised."), LS, 0)
    launch("Leibnitz CB7",  1961,  6, 29, LeibnitzCB,   Payload("Lagrange Hab A", "First of two two-man habitation modules for Lagrange Space Station."), LEO, 0)
    launch("Leibnitz CE3",  1961,  7,  5, LeibnitzCE3,  Payload("Bacon 3", "Comsat.", "1084CSP"), GEO, 0)
    launch("Leibnitz CC5",  1961,  8, 11, LeibnitzCC5,  Payload("Laplace 5", "Softlanding lunar probe."), LS, 0)
    launch("Locke 2B0",     1961,  8, 20, Locke2B0,     paren("1.25 tons lead ballast"), LEO, 0)
    launch("Leibnitz CB8",  1961,  9,  8, LeibnitzCB,   Payload("Lagrange Hab B", "Second of two two-man habitation modules for Lagrange Space Station."), LEO, 0)
    launch("Locke 2B1",     1961, 10, 19, Locke2B,      Payload("Hobbes 1", "Cargo supply ship to Lagrange Space Station.", "~68 man-days of LS."), LEO, 0)
    launch("Leibnitz DC1",  1961, 11,  7, LeibnitzDC,   Payload("Copernicus 5", "Lone Mercury fly-by probe."), HF, 0)
    launch("Leibnitz DH1",  1961, 11, 18, LeibnitzDH,   Payload("NTF-1", "First crew to Lagrange Space Station.", ("Timur Vasilyevykh", "Vasily Sungatulin")), LEO, 0)
    launch("Leibnitz DC2",  1961, 12, 22, LeibnitzDC2,  Payload("Barrow 1", "Lunar propellant depot/delivery.", "~700kg of 50-50 and NTO"), LO, 0)
    launch("Leibnitz DE1",  1962,  1,  1, LeibnitzDC2,  Payload("Bacon S1", "Comsat, first of four-sat network."), GEO, 0)
    launch("Leibnitz DC2₂", 1962,  1, 12, LeibnitzDC2,  Payload("Barrow 2", "Lunar propellant depot/delivery.", "~700kg of 50-50 and NTO"), LO, 0)
    launch("Leibnitz DC3",  1962,  3,  1, LeibnitzDC2,  Payload("Laplace 6", "Lunar lander with ascent stage for sample return."), LSR, 0)
    launch("Euler 0",       1962,  3, 13, Euler0,       paren("9 tons lead ballast"), LEO, (1, 1, 2)) # failures galore!  Barely made it off the launchpad
    launch("Leibnitz DC2₃", 1962,  4, 12, LeibnitzDC2,  Payload("Barrow 3", "Lunar propellant depot/delivery.", "~700kg of 50-50 and NTO"), LO, 0)
    launch("Leibnitz DE2",  1962,  5,  2, LeibnitzDE2,  Payload("Bacon S2", "Comsat, part of four-sat network."), GEO, 0)
    launch("Leibnitz DD1",  1962,  5, 10, LeibnitzDD,   Payload("Barrow 4", "Space tug to bring Laplace 6 back down to LEO."), EO, 0)
    launch("Euler A1",      1962,  6,  4, EulerA,       Payload("Copernicus 6", "First outer-planet probe."), JF, 0) # XXX provisional marking of success; probe still en route
    launch("Leibnitz DH2",  1962,  6, 16, LeibnitzDH,   Payload("NTF-2", "Second crew to Lagrange Space Station.", ("Eric Welch", "Catherine Graves")), LEO, 0)
    launch("Leibnitz DE2₂", 1962,  7, 16, LeibnitzDE2,  Payload("Bacon S3", "Comsat, part of four-sat network."), GEO, 0)
    launch("Leibnitz DH3",  1962,  7, 23, LeibnitzDH3,  Payload("NEF-6", "Fetching back samples from Laplace 6.", "Brian Newman"), LEO, 0)
    launch("Leibnitz DB1",  1962,  8, 21, LeibnitzDB,   Payload("Fahrenheit 1", "First planetary lander probe."), VS, -1) # destroyed in hard landing
    launch("Leibnitz DE2₃", 1962,  8, 29, LeibnitzDE2,  Payload("Bacon S4", "Comsat, last of four-sat network."), GEO, 0)
    launch("Leibnitz DH4",  1962, 10,  2, LeibnitzDH,   Payload("NTF-3", "Third crew to Lagrange Space Station.", ("Timur Vasilyevykh", "Nikolay Tikhonov")), LEO, 0)
    launch("Leibnitz DB2",  1962, 10, 16, LeibnitzDB,   Payload("Copernicus 7", "Mars orbiter / martian moon flyby."), FF, 0) # XXX provisional marking of success; probe still en route to Mars
    launch("Locke 2B2",     1962, 10, 17, Locke2B,      Payload("Hobbes 2", "Cargo supply ship to Lagrange Space Station.", "~68 man-days of LS."), LEO, 0)
    launch("Leibnitz DH5",  1962, 10, 23, LeibnitzDH5,  Payload("NTF-4", "Crew rotation; first time two vehicles (and four crew) are at Lagrange Space Station.", ("Eric Welch", "Catherine Graves")), LEO, 0) # technically the AgenaF had a failure to ignite, but we succeeded in lighting it on the second try, and it has plenty of ignitions to spare # XXX provisional marking of success; still on-orbit at Station
    launch("Leibnitz DE3",  1962, 10, 27, LeibnitzDE3,  Payload("D'Alembert 1", "Lunar rover."), LS, 4) # ignition failure on the mini-DeltaD
    launch("Locke 2B3",     1962, 11,  2, Locke2B,      Payload("Hobbes 3", "Cargo supply ship to Lagrange Space Station.", "~50 man-days of LS."), LEO, 0)

    print "%d launches recorded" % (len(launches),)
    return Database(launches)

if __name__ == '__main__':
    import optparse
    x = optparse.OptionParser()
    x.add_option('-w', '--web', action='store_true')
    x.add_option('-p', '--port', type='int', help='TCP port number to serve', default=8080)
    opts, args = x.parse_args()
    if args:
        x.error("Unexpected positional arguments")
    db = testdb()
    if opts.web:
        serve_web(db, opts.port)
    else:
        test_html(db)
        test_text(db)
